name: Publish Ruby Gem (Pushed)

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish gem
        uses: jstastny/publish-gem-to-github@v2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: acima-credit
